### ISSUE TITLE
Set_RulesFile missing

### ISSUE THREAD

**Issue by rinseaid** [damienvanrobaeys/MDT_INI_Selector#1]
Hi there, thanks for this tool.

In the post on your website, you mention a file called Set_RulesFile.wsf, which is missing from the repository. For anyone else looking to use this tool, run the executable with ProcMon running and you'll see a directory created in \users\<username>\appdata\local\temp named Make-EXE0. Copy this directory, and inside it you'll find Set_RulesFile.wsf which you can copy Extra\Deploy\Scripts in your DeploymentShare.

**Comment by damienvanrobaeys** [comment]
Just uploaded the file
